### ISSUE TITLE
How to process the consumption data you get from ovc.account.get_consumption()

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/lib9#113]
#### Installation information

- jumpscale version: master (9.3.0)
- operating system: Ubuntu

#### Detailed description

Using the OpenvCloud client you get get the consumption data for an account by executing the below code:
```python
resp = account.get_consumption(start, end)
```

This `resp` is a zip file. 

I'm looking for some example code that shows how to process this data using `j.tools.tarfile`.

**Comment by despiegk** [comment]
will be obsolute, all to do with capacity planning will be done differently
