### ISSUE TITLE
new argument `sshkeypath` is not documented in docstring of `machine_create()`

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/lib9#141]
#### Installation information

- jumpscale version: 9.3.0

#### Detailed description

New argument was added to signature of `machine_create()` but documentation was not updated.

![screen shot 2017-12-18 at 16 15 53](https://user-images.githubusercontent.com/13795109/34113596-82d9df54-e410-11e7-94c0-13c1ba0b95be.png)

**Comment by rkhamis** [comment]
already fixed
