### ISSUE TITLE
OVC client > machine_create() "sshkeyname" argument can't work for Windows

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/lib9#142]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu

#### Detailed description

`machine_create(...)` has a mandatory parameter "sshkeyname", which causes problems when provisioning Windows VMs. Machine get created successfully, but the method fails; because SSH is not available/enabled on Windows system images by default.

Relates to https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/380

**Comment by rkhamis** [comment]
Make the sshkeyname parameter optional and check if not passed, skip

**Comment by svs1370** [comment]
Please note that after the latest fix there are now two "sshkeyname" arguments to the "machine_create()" method.
![image](https://user-images.githubusercontent.com/34687689/34245156-c2e0828a-e639-11e7-9c8d-7d363e0ae75f.png)
