### ISSUE TITLE
JS vm.model shows 'Undefined' IP address for a fully functional VM

### ISSUE THREAD

**Issue by svs1370** [Jumpscale/lib9#143]
After creating a Windows based VM using JS 9.3.0 machine_create() method, it is not possible to obtain VM's internal IP address by either:
* accessing tmp_vm.model["nics"][0]["ipAddress"] - returns 'Undefined'
* calling tmp_vm.machineip_get() method - returns error (see the screenshot below)
![image](https://user-images.githubusercontent.com/34687689/34168074-8e9d8108-e4f4-11e7-974d-3a0f459ac1c9.png)

Both attempts to obtain IP address were made with substantial time lapsed since the moment the VM was created.

At the same time OVC web interface shows valid IP address for this VM.

**Comment by svs1370** [comment]
Also no portforwards are actually created for such VM when calling tmp_vm.portforward_create(...)

**Comment by rkhamis** [comment]
@svs1370 

I tested with image `Windows 2012r2 Standard`, here's what I get:

```
In [27]: machine.model['nics'][0]['ipAddress']
Out[27]: '192.168.103.253'
```

and again with `Windows 2016` and got back an ip.


Could you perhaps tell me which environment this was on?

**Comment by svs1370** [comment]
It was and still is on MR4.demo.greenitglobe.com


21 дек. 2017 г. 1:53 ПП пользователь "Reem Khamis" <notifications@github.com>
написал:

**Comment by svs1370** [comment]
Any progerss with the debugging and understanding the root cause?

Please note that I am getting the same on DS1 with Linux machines.
I am using JS 9.3.0 with the latest bug fixes, and here is what I get after
2+ minutes (which is excessive time!) when calling the following method:

METHOD I AM CALLING>>>
print('Creating VM with the role {}'.format("Proxy"))
proxy_vm = vdc.machine_create("Proxy", disksize = "10", vcpus = 2, memsize
= 4, image = OSImageName, description = 'DE Portal Sandbox - Proxy')
proxy_vm.portforward_create(16122, 22, 'tcp')
proxy_vm.portforward_create(80, 80, 'tcp')

ERROR OUTPUT>>>>
Creating VM with the role Proxy
Cloud space ID:13 name:Proxy size:3 image:1 disksize:10
Traceback (most recent call last):
  File "./Scripts/DEPortalSandbox.py", line 52, in <module>
    proxy_vm.portforward_create(16122, 22, 'tcp')
  File
"/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/OpenvCloudClientFactory.py",
line 900, in portforward_create
    machineip, _ = self.machineip_get()
  File
"/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/OpenvCloudClientFactory.py",
line 972, in machineip_get
    "Could not get IP Address for machine %(name)s" % machine)
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Could not get IP
Address for machine Proxy ((type:runtime.error)
Could not get IP Address for machine Proxy

**Comment by svs1370** [comment]
Also note that in the above example the VM created quite quickly, but port forward creation method takes 2+ minutes before reporting the error.
The issue persists in both MR4 and DS1 using JS 9.3.0, no matter Windows or Linux VM

**Comment by svs1370** [comment]
The same bug is observed when trying to obtain internal IP of a VM, created with JS 9.3.0, from a production AYS Server running JS 9.2.0!

**Comment by svs1370** [comment]
The same bug is observed whtn creating a VM with JS 9.2.0 - JS returns "undefined", while OVC portal shows valid internal IP.
So there is no difference between JS versions.

**Comment by svs1370** [comment]
One more test - I've manually created a Linux VM on DS1 using OVC web portal, and it has a valid internal IP address in the OVC panel.

Below I summarize what I get when try to obtain internal IP addredd by various methods:
1) vm.model shows 'Undefined' 
2) vm.machineip_get shows valid IP address (along with a bunch of other info)

vm.portforward_create(XXXX22,22) also works as expected.

So there seems to be a discrepancy in what vm.model contains and what other methods return. As a consequence, any method that relies on information from vm.model may not always work correctly.

**Comment by rkhamis** [comment]
I checked indeed on the env. It seems there's an environment issue. I notified ops and will update when they get back to me

**Comment by rkhamis** [comment]
Fixed in latest ovc releases
