### ISSUE TITLE
finish tests: `js9_raml test`

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/lib9#148]
see inside method to know what to do

**Comment by zaibon** [comment]
WIP : https://github.com/Jumpscale/lib9/commit/3efcaf69022ce22e2b62b59f9521f261e5b12262

- had to fix IYO client first, so I regenerated it properly and fix the
raml spec
- implement the test of raml tool. But the tool itself miss some code to
make the test pass

Still to be done: write code to generate golang server
test lua generation, I didn't managed to generate lua code, only capnp schemas...

**Comment by rkhamis** [comment]
Done for python.

Lua would require tarantool installation and its dependencies and the generated server has nothing to verify
