### ISSUE TITLE
j.tools.raml not working as it should yet

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/lib9#155]
![image](https://user-images.githubusercontent.com/6021844/34402810-dfb3f018-ebac-11e7-93bc-67ac47eade6d.png)

generated should have all the generated code

the server directory should be minimal (it was like that before)

- only the files which needs to be rewritten e.g. group_api.py everything else is not supposed to be overwritten

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/34402865-419b83e0-ebad-11e7-89ea-52e14d8bd968.png)

server needs to be generated in here too and then only relevant files copied to 
/tmp/ramltest/server

**Comment by serboctor** [comment]
go-raml doesn't support this, the imports and the way it generates needs to be changes. This task is blocked on https://github.com/Jumpscale/go-raml/issues/393.

**Comment by serboctor** [comment]
This generated structure is not needed any more, we re-factored go-raml to always regenerate all the files except for the api method handlers which will include the user's implementation(located under /handlers). We also added clear comments at the top of all the templates stating if a file is safe to edit or not. This change has already been done in the python client/server generator and is being applied to the rest of the generators.

Relevant tasks:
https://github.com/Jumpscale/go-raml/issues/405
https://github.com/Jumpscale/go-raml/issues/406
