### ISSUE TITLE
openvcloud client: security approach

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/lib9#156]
![image](https://user-images.githubusercontent.com/6021844/34433707-add93c14-ec89-11e7-9bf6-b620620f4515.png)

the jwt token is so generic, how can this ever work?
shouldn't there be a scope asked for? different then user:admin?
shouldn't there be a connection with a group as defined on IYO

now its all too vague in my opinion

**Comment by yveskerwyn** [comment]
regarding the connection with a group as defined in IYO, see my FR: https://github.com/0-complexity/openvcloud/issues/858 

as discussed w/ @FastGeert we need IYO group integration in OVC
