### ISSUE TITLE
add 0-core client to install_requires in setup.py

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/lib9#16]
see: https://github.com/Jumpscale/lib9/blob/master/setup.py#L17
Why do we install pip packages like that ?
It has to be in the `install_requires` list of the `setup` method

**Comment by ahussein** [comment]
we had a problem during installation of the lib package when the 0-core-client package was added to the install_requires. The problem is already reported in https://github.com/zero-os/0-core/issues/352

We should keep this ticket open and follow up on the related ticket.
