### ISSUE TITLE
Update ssh method names

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/lib9#160]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu 16.04

#### Detailed description

Currently we have inconsistent naming formats for the SSH client.

Update the method names for the following methods:
- `j.clients.ssh.SSHKeyGetPathFromAgent()`
- `j.clients.ssh.SSHKeyGetFromAgentPub()`

Suggested new names:
- `j.clients.ssh.get_key_path()`
- `j.clients.ssh.get_public_key()`

**Comment by despiegk** [comment]
this is not the convention, is always obj_method

e.g. pubkey_get
and anyhow this is really the wrong version you're looking on

**Comment by despiegk** [comment]
is done in 930_ssh

**Comment by yveskerwyn** [comment]
@despiegk After the 930_ssh merge into development I still see this:
![screen shot 2018-02-27 at 18 07 19](https://user-images.githubusercontent.com/13795109/36742936-496984de-1be9-11e8-9f00-488890138908.png)

**Comment by rkhamis** [comment]
@yveskerwyn 9.3.0_ssh hasn't been merged yet into development. The merge is on merge_branches. it's clean there
