### ISSUE TITLE
itsyou.online client

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/lib9#169]
see on branch 930_ssh

- seems goraml is not generated properly
- why are all methods in capital letters?
- get error on test
- can't get the test to work at all, is username required?
- if username is required, is there a way to fetch the username automatically? I thought this was gone the username.

![image](https://user-images.githubusercontent.com/6021844/35846086-94909860-0b2e-11e8-9012-5efcfc584623.png)

remark: jwt works because its separate call, but seems to be only thing working

**Comment by arahmanhamdy** [comment]
The method names are uppercase because it's generated from displayname of the raml file which is uppercase (https://github.com/itsyouonline/identityserver/blob/master/specifications/api/itsyouonline.raml#L633)

The username was removed from the template and the test is updated to get it from jwt
