### ISSUE TITLE
rivine client

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/lib9#179]
Requirements:
- client need to be able to create transaction with custom data inside.
this is going to be used by the 0-robot when registering capacity or creating reservation 
- client needs to be able to query the blockchain to read reservation and any other information that has been put on the blockchain.

In order to be able to create transaction, the 0-robot need to consume some token to pay the fee to the rivine network.
Which means the 0-robot will need to have a wallet and/or address which it can used to pay fees

Example how to create transaction: https://github.com/rivine/rivine/tree/master/doc/examples/offline_transaction

@robvanmieghem @LeeSmet feel free to comment on this.

After a disscussion with @robvanmieghem , seems the easiest way to achieve this, is to make the client talk to an explorer node. An explorer node will expose an API to quey the blockchain, but also send new transaction.
So the client will need to implement some kind of ligth wallet where it can know how much token is available for a certain address and create offline transaction

**Comment by robvanmieghem** [comment]
> where it can know how much token is available for a certain address and create offline transaction

It can do so just by querying an explorer node,

**Comment by LeeSmet** [comment]
There is an explorer running for the testnet: http://185.69.166.13:2015/

The explorer allows looking up hashes (addresses, txids, blockids,...), and posting a new transaction. The transaction must be signed, which means that some sort of ligthweight wallet needs to be implemented. A small one is implemented in the go script in the linked example above. Basically, the wallet will need the following functionality:
- Starting from a seed, be able to derive the public and private keypairs.
- Use the public keys to create unlockcondition objects, which can be hashed to get the addresses.
- These addresses can be used to query the explorer to get the coininputs
- Remove those that are already spent
- When creating the transaction, select the coin inputs to have equal or more coins than the required output + minerfee. Change can be written back to one of your own addresses. Note that an input must be consumed in its entirety.
- For every public key in the input, the corresponding private key is required to sign the transaction to be valid

For querying the chain and storing data (creating txns), this should suffice. Note that you will need a seed to start with which has some addresses with unused coin inputs (so you have funds) to create the txn

**Comment by ahussein** [comment]
Talked to @LeeSmet  about the word list currently used by rivine for generating seeds, and we will need to use the more standard BIP-0039 since it will be used in rivine as well according to: https://github.com/rivine/rivine/issues/116

**Comment by ahussein** [comment]
Code complete on https://github.com/Jumpscale/lib9/tree/rivine_client/JumpScale9Lib/clients/rivine
Still need to test the creation and pushing transactions on the testnet after getting some seed that has some funds on it. Also still need to write some unittests, right now we have only one test script for sanity check.

**Comment by ahussein** [comment]
@zaibon  please verify that the library provide the required functionalities required by the 0-robot and then we can merge to development.
