### ISSUE TITLE
j.clients.ssh.ssh_keys_load() doesn't load key

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/lib9#181]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu 9.3.0 (development)

#### Detailed description

When using `j.clients.ssh.ssh_keys_load(path=ssh_key_path)` a new key is created, but doesn't get loaded.

#### Steps to reproduce

```python
import os
ssh_key_name = "new_key"
ssh_key_path = os.path.expanduser("~/.ssh/{}".format(ssh_key_name))
j.clients.ssh.ssh_keys_load(path=ssh_key_path)
j.clients.ssh.ssh_keys_list_from_agent()
```

**Comment by yveskerwyn** [comment]
Problem solved if using `j.clients.ssh.load_ssh_key(path=ssh_key_path, create_keys=True)` instead of  `j.clients.ssh.ssh_keys_load(path=ssh_key_path)`

But why do we have both methods? Can we have this functionality in one method?

**Comment by rkhamis** [comment]
Closing this because it's obsolete
