### ISSUE TITLE
Story: building and running flists from zeroos

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/lib9#186]
The scenario will be as following:

from JumpScale,

1. create a zero-os node
2. boot up an ubuntu vm inside it
3. Use prefab to build any solution
4. Sandbox result
5. upload to 0-hub
6. create a new vm with new flist

**Comment by xmonader** [comment]
Progress update only reached the stage of booting an ubuntu flist and uploading keys into it with minimal hack on openvcloud client to stop sshauthorization
