### ISSUE TITLE
Review and client zerotier sal

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/lib9#201]
The current zerotier sal is not that very useful.

Need to be able to:
```python
zc = j.clients.zerotier.get(name="geert", token="jkhljhbljb")
mynetworks = zc.list_networks()-> [ZerotierNetwork]
mynetwork = zc.get_network(networkid='khgfghvhgv') -> ZerotierNetwork
zc.create_network(public=True, subnet="10.0.0.0/24", auto_assign=True, routes=[])
mymembers = mynetwork.list_members() -> [ZerotierNetworkMember]
mymember = mynetwork.get_member(address='hfivivk' || name='geert' || public_ip='...' || private_ip='...')
mymember.authorize()
mymember.deauthorize()
```

**Comment by despiegk** [comment]
please check with me

**Comment by ahussein** [comment]
tried to reach @despiegk but could not.
@FastGeert  I have pushed the changes to zerotier_refactor branch where you can check if the interface and functionality is what you expected. Also you can check the test code for an example of how to use the client:  https://github.com/Jumpscale/lib9/blob/zerotier_refactor/tests/clients/zerotier/test_ZerotierClient.py

**Comment by despiegk** [comment]
accepted the channges, thx

**Comment by ahussein** [comment]
Still need to change the code that used to call the old client API
