### ISSUE TITLE
Harden start method of thchain blockcreator / explorer sal.

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/lib9#210]
Check if port is listening rather then just verifying if the process is running.

See example in: https://github.com/Jumpscale/lib9/blob/development/JumpScale9Lib/clients/zero_os/sal/ZeroRobot.py#L61

**Comment by khaledkbadr** [comment]
done in https://github.com/Jumpscale/lib9/commit/3b34003ad925747d67e5d7a32031cb3199533dbb
