### ISSUE TITLE
zeroboot client

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/lib9#220]
# Scope
Using the zero boot client we will be able to configure a remote zero boot server (OpenWRT) from jumpscale over a zerotier network. The following actions need to be available:
- create a network in the dhcp server (subnet, dns)
- add hosts to a network (macaddress / ipaddress / hostname)
- list networks / hosts
- delete networks / hosts
- power-cycle hosts (on, off, off/on)

# Interface
```python
bootclient = j.client.zeroboot.get("dubai-01")

# Create a new network
dubainet = bootclient.networks.add("192.168.0.0/24", ["8.8.8.8"])

# Add a host to a network
rack_01_machine01 = dubainet.hosts.add("00:00:00:00:00:01", "192.168.0.10", "rack_01_machine01")

# Power features
rackclient = j.clients.racktivity.get("rack01_left")
bootclient.power_on(rackclient, 5) # port 5
bootclient.power_off(rackclient, 5)
bootclient.power_cycle(rackclient, 5) # == power off, sleep 5, power on

# Get a host
dubainet.hosts["rack_01_machine01"]

# List the hosts
for host in dubainet.hosts:
    print(host.name)

# Remove a host
dubainet.hosts.remove("rack_01_machine01")

# Show host details
print(rack_01_machine01.mac)
...

# Same getting / deleting / listing functions need to be present for the networks
# Client also needs to do the necessary checks to prevent double host registrations / ip address conflicts 
# Client needs to be stateless. This means that it needs to get its data by reading configuration values from the uci.

**Comment by alichaddad** [comment]
To see work check here https://github.com/Jumpscale/lib9/tree/zboot-cli. Still need to implement creating network in the dhcp server.

**Comment by zaibon** [comment]
We'll also need a way to configure the ipxe image used to boot the nodes.
Would be nice if we could even choose this per node
