### ISSUE TITLE
 jwt gets expired it cannot refresh automatically

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/lib9#242]
# issue

When jwt gets expired it cannot refresh automatically, today you need full IYO client authenticated, 
the jwt should be able to get refreshed without needing your secret of IYO.

We need this in repo's where we work together on IT environments, otherwise people get stuck with JWT refresh issues all the time

code  see https://github.com/Jumpscale/lib9/tree/master/JumpScale9Lib/clients/itsyouonline

**Comment by rkhamis** [comment]
@despiegk is your JWT already refreshable?

**Comment by alichaddad** [comment]
This is already supported in itsyouonline. You first have to make sure that the jwt is refreshable. 
Using Js9:
```python
jwt = client.jwt_get(refreshable=True)
``` 
Then without using a itsyouonline client it is possible to refresh this jwt:

```python
j.clients.itsyouonline.refresh_jwt_token(jwt)
```
The above will only refresh if the jwt needs refreshing.

**Comment by arahmanhamdy** [comment]
fixed in itenv_test repo
https://docs.grid.tf/despiegk/itenv_test/commit/2c14acbfbc2e9792df21006390c67f9fed8b24a2

**Comment by ahmedelsayed-93** [comment]
verified
