### ISSUE TITLE
All the dependent libraries should be installed by the default

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/lib9#269]
**Description**
I used bash tool to install js9 from the development branch and I found that there are lots of dependent libraries weren't installed by the default. 

**Expected Result**
All the dependent libraries should be installed by the default

**Examples**
![image](https://user-images.githubusercontent.com/17981089/40063021-b576c736-585c-11e8-83d7-a37114c8cbe5.png)

![image](https://user-images.githubusercontent.com/17981089/40063039-beddf178-585c-11e8-811d-6a697900f18f.png)

![image](https://user-images.githubusercontent.com/17981089/40063058-c790c48a-585c-11e8-91aa-aa10eb0f909d.png)

- jumpscale version:
development 

- operating system:
ubuntu 16.04

**Comment by rkhamis** [comment]
That's by design. If we add all the dependencies, the installation of jumpscale would take too long. Developers should be aware that they have to have dependencies to use some modules
