### ISSUE TITLE
Add farmer sign in form in the grid capacity web site

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/lib9#272]
Code location: https://github.com/Jumpscale/lib9/tree/capacityfarmers/JumpScale9Lib/servers/grid_capacity

We need to add a sign in form for the farmer to register themself as farmer.
This form will do a oauth flow to IYO to validate that the use is actually register on IYO.
I should also be possible for a farmer to register an organization in that case the sign in form will validate that the use is member of this organization. That will validate that the organization actually exists and that the farmer has right on it

**Comment by grimpy** [comment]
Done

**Comment by ahmedelsayed-93** [comment]
verified
