### ISSUE TITLE
Calling machine_get(...) for an existing Linux and Windows VMs without port forward rule to port 22 returns error

### ISSUE THREAD

**Issue by svs1370** [Jumpscale/lib9#294]
#### Installation information

- jumpscale version: JS 9.3.x master
- operating system: JS is installed on Ubuntu 16.04, target VM is also Ubuntu 16.04

#### Detailed description
Attempt to obtain a handle to existing VM using machine_get(..) method returns an error if no port forward to 22 for this VM exists

#### Steps to reproduce
For preexisting cloud space with an Ubuntu VM in it:
tmp_vm=proxy_vdc.machine_get(ProxySrvName, create=False)

#### Relevant stacktraces
```
tmp_vm=proxy_vdc.machine_get(ProxySrvName, create=False)

/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Space.py in machine_get(self, name, create, sshkeyname, memsize, vcpus, disksize, datadisks, image, sizeId, stackId, reset, managed_private, authorize_ssh)
    207         if authorize_ssh:
    208             if not managed_private:
--> 209                 self._node_set(machine.name, machine.sshclient)
    210             else:
    211                 self._node_set(machine.name+'_private', machine.sshclient_private)

/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Machine.py in sshclient(self)
    337
    338         if self._sshclient is None:
--> 339             addr, port = self._ssh_info()
    340             key = self._ssh_client_key(addr, port, "root")
    341             self._sshclient = j.clients.ssh.new(instance=key, addr=addr, port=port, login="root", passwd="",

/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/Machine.py in _ssh_info(self)
    367         # error if port 22 is not found
    368         if not addr or not port:
--> 369             raise RuntimeError("VM '%s' doesn't have ssh port 22 exposed" % self.name)
    370
    371         return addr, port

RuntimeError: VM 'ProxyVM' doesn't have ssh port 22 exposed
```

**Comment by svs1370** [comment]
The same error is generated when trying use machine_get(...) method on preexisting Windows VM that naturally does not have its 22 port exposed.

**Comment by alichaddad** [comment]
By default the client tries to get an ssh connection to the machine to disable this behavior set the flag `authorize_ssh` to False as follows:
```python
tmp_vm=proxy_vdc.machine_get(ProxySrvName, create=False, authorize_ssh=False)
```

**Comment by svs1370** [comment]
Thank you for the clue.
I've tested machine_get(...) with authorize_ssh=False for a Linux VM and a Windows VM that donot have their 22 port exposed - completed without errors.
