### ISSUE TITLE
machine doesn't join zerotier after boot it with zboot 

### ISSUE THREAD

**Issue by Dinaamagdy** [Jumpscale/lib9#311]
- boot cpu-1 on be-scale-2 with the following lkrn 
```http://unsecure.bootstrap.gig.tech/krn/development/8850338390f481e6/development```
## Issue
the node doesn't join the zerotier network

**Comment by ahussein** [comment]
How this is related to js libs?
The libs will only authorize the node after joining the network. Joining the network is a ZOS task.
