### ISSUE TITLE
lib9 rivine wallet: NonSia specifier no longer supported

### ISSUE THREAD

**Issue by GlenDC** [Jumpscale/lib9#312]
The `NonSia` specifier is no longer supported by Rivine since a couple of versions ago.

Looking at the lib9 code I still see references to it however:

https://github.com/Jumpscale/lib9/blob/8efa0382b35f0c738d736b76368b264a4a94ed94/JumpScale9Lib/clients/rivine/types/signatures.py#L9

**Comment by ahussein** [comment]
This needs cleanup, the constant is not used anywhere though.

**Comment by ahussein** [comment]
Fixed development branch
