### ISSUE TITLE
lib9 rivine wallet: missing support for v0 transaction

### ISSUE THREAD

**Issue by GlenDC** [Jumpscale/lib9#313]
I seem to not find any support for v0 transactions in the lib9 rivine wallet code.
Only for v1 transactions I seem to find support.

Code reference: https://github.com/Jumpscale/lib9/blob/rivinewalletv1.0.5/JumpScale9Lib/clients/rivine/types/transaction.py#L12

**Comment by ahussein** [comment]
What do you mean by transaction v0 support. For creating transactions it's
idd not supported but for syncing the wallet, the library will understand
and get the info of the existing transactions from both v0 and v1

**Comment by GlenDC** [comment]
Yes I'm sorry, when reading code such as https://github.com/Jumpscale/lib9/blob/8efa0382b35f0c738d736b76368b264a4a94ed94/JumpScale9Lib/clients/rivine/RivineWallet.py#L229-L250, it does seem like you'll be able to understand both formats.

You can close this issue as invalid.

**Comment by ahussein** [comment]
Not an issue
