### ISSUE TITLE
lib9 rivine wallet: missing unit tests for encoding and signature computations

### ISSUE THREAD

**Issue by GlenDC** [Jumpscale/lib9#314]
None of the Rivine Wallet code in this lib9 repository is tested against unit tests. Meaning there is no guarantee that I can find, as to guarantee the results computed by the lib9 library are the same as the results produces by the Rivine Golang Reference implementation.

This is a shame, as the reference implementation does provide ready-to-copy unit test cases that could be applied to any other full/light implementation:

+ Expected binary (hex-encoded) signatures for both v0 and v1 transactions: https://github.com/rivine/rivine/blob/master/types/signatures_doc_test.go
+ Expected binary (hex-encoded) signatures for both v0 and v1 transactions, and as this tests all possible binary encoding primitives required also for signatures it is a unit test that gives a lot of coverage on a useful high level: https://github.com/rivine/rivine/blob/0d763d77b75608ceee476fd09cf42ab8da05b1eb/types/transactions_test.go#L168-L619
+ Expected JSON-encoding for both v0 and v1 transactions, useful to know you produce the correct structure as expected by daemons your client interacts with over RPCs: https://github.com/rivine/rivine/blob/0d763d77b75608ceee476fd09cf42ab8da05b1eb/types/transactions_test.go#L696-L1565
+ Expected binary (hex-encoded) conditions, used to lock outputs since v1 transactions (and used as primitives for the signature computation): https://github.com/rivine/rivine/blob/0d763d77b75608ceee476fd09cf42ab8da05b1eb/types/unlockcondition_test.go#L17-L29
+ Expected binary (hex-encoded) fulfillments, used to unlock outputs since v1 transactions: https://github.com/rivine/rivine/blob/0d763d77b75608ceee476fd09cf42ab8da05b1eb/types/unlockcondition_test.go#L81-L90
+ Expected JSON-encoding of conditions, used to lock outputs (useful to have such lower level tests to guarantee the JSON encoding, part of your JSON transactions, are already in a proper format): https://github.com/rivine/rivine/blob/0d763d77b75608ceee476fd09cf42ab8da05b1eb/types/unlockcondition_test.go#L142-L229
+ Expected JSON-encoding of fulfillments, used to unlock outputs (useful to have such lower level tests to guarantee the JSON encoding, part of your JSON transactions, are already in a proper format): https://github.com/rivine/rivine/blob/0d763d77b75608ceee476fd09cf42ab8da05b1eb/types/unlockcondition_test.go#L258-L354

**Comment by ahussein** [comment]
Unit tests are planned after making a working version of the client first.

**Comment by GlenDC** [comment]
I do not see how you can get to a working version if not with unit tests? Seems like a very weird approach... Until than you're just going to swing and guess it? I'm sure you can do it, but it does not seem like a very effective way of doing so.

**Comment by ahussein** [comment]
Yes, I agree.

**Comment by ahussein** [comment]
added basic test coverage for binary encoding, signature generation, and transactions

**Comment by ahussein** [comment]
merged to development
