### ISSUE TITLE
Joining  a ZT from Mac using prefab fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/lib9#317]
#### Installation information

- jumpscale version: development (9.4.0 rc4)
- operating system: Mac

#### Detailed description

When trying to join a ZT network from Mac using prefab, `zerotier-cli` is being looked for in the directory `/Users/yves/opt/bin/`, which is an empty directory on my Mac.

ZeroTier is installed in another directory on my Mac:
```bash
which zerotier-cli
/usr/local/bin/zerotier-cli
```

Trying the reinstall ZT using prefab didn't help, it rather revealed another issue, as reported here: https://github.com/Jumpscale/core9/issues/237

#### Steps to reproduce

![screen shot 2018-06-15 at 10 48 32](https://user-images.githubusercontent.com/13795109/41459927-4d651dfe-708b-11e8-9a5e-e0f228da807d.png)

**Comment by ashraffouda** [comment]
fixed by fixing this https://github.com/Jumpscale/core9/issues/237

**Comment by yveskerwyn** [comment]
thanks, verified, works for me, closing
