### ISSUE TITLE
could not import JumpScale9Lib.clients.gogs.GogsFactory (GogsFactory)

### ISSUE THREAD

**Issue by Dinaamagdy** [Jumpscale/lib9#33]
## Steps 
- install js9 
-  js9_start

## Error 
```
COULD NOT IMPORT:JumpScale9Lib.clients.gogs.GogsFactory (GogsFactory)

import error:
No module named 'issuemanagerlib'



COULD NOT IMPORT:JumpScale9Lib.clients.github.Github (GitHubFactory)

import error:
No module named 'issuemanagerlib'



COULD NOT IMPORT:JumpScale9Lib.tools.xonsh.Xonsh (Xonsh)

import error:
No module named 'xonsh'

```

## Software Version 
lib9 version : ee20d0923916b10b085ca0b3af505ef08b9754ff

**Comment by xmonader** [comment]
Fixed by: https://github.com/Jumpscale/lib9/pull/32 please verify

**Comment by rkhamis** [comment]
This is by design.
Libs has a lot of clients of non-core modules. They should be installed in order to use those clients. These are just warnings
