### ISSUE TITLE
Grid capacity: find a way to validate the capacity registered is real

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/lib9#332]
In this issue we want to discuss a way for the capacity website to be able to validate that the request for capacity registration are really coming from 0-os.

Currently the capacity API only check that the farmer_id send in the capacity registration request is valid.
But there is not check on the actual capacity values. Which means any farmer could fake the capacity and send false number to the API. 

To prevent this, we could make the node robot sign the capacity request with its private key. Then the capacity website when receiving the capacity registration request, would dial to the node robot and check its public key in order to be able to verify the signature.

That would bring 2 benefits:
- we make the capacity registered more likely to be correct
- we check that the node is actually reachable, information that we will need to compute the SAL of the farm

**Comment by muhamadazmy** [comment]
I think your solution fixes some of the issues but not everything. it is still possible for a "smart" farmer to run the 0-robot code on an "for example" ubuntu machine behind Caddy. And still manage to fake the capacity? your verification only verifies that the robot is running and is reachable and it can sign requests. 

A similar workaround is the farmer can run a node in development node and has a full access where he can manipulate 0-robot files and signature.

What we need to validate actually is that the robot code is running on a genuine zos node in production mode.

I actually can't think (at least now) for a fix for this issue. I hope other people can help more.

**Comment by zaibon** [comment]
Yes this doesn't prevent people to still fake capacity indeed. Actually my solution doesn't really bring anything new. So I think a long as we don't have proper proof of capacity system. there is no point trying to secure this in another way.
