### ISSUE TITLE
kubernetes js93 client

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/lib9#75]
see https://github.com/Jumpscale/lib9/blob/9.3.0/JumpScale9Lib/clients/kubernetes/KubernetesFactory.py

make sure its nice DSL, easy to use

**Comment by despiegk** [comment]
see also https://github.com/Incubaid/kubernetes

**Comment by despiegk** [comment]
one of results should be we can use this client to
- on any kubernetes destination (google, minikube, openvcloud kubernetes)
- deploy ubuntu base with ssh key authenticated (use prefab functionality)
- result is prefab client which can be used to further build, ...

**Comment by abdulrahmantkhalifa** [comment]
the basic functionality  is implemented with the wrapper classes, ill finish the readme tomorrow  but need more time for the  Prefabkubernetes(the single node build and install are done but multiple host deployment needs more time) to be implemented  and to figure out the cluster deployment strategy required , all relevant code will be on 9.3.0_kubernetes branch on lib9 repo and prefab9 repo
