### ISSUE TITLE
j.clients.ssh.loadSSHAgent(createkeys=True) doesn't create a new key

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/lib9#82]
#### Installation information

- jumpscale version: 9.2 (master)
- operating system: Ubuntu 16.04

#### Detailed description

`j.clients.ssh.loadSSHAgent(createkeys=True)` does start ssh-agent, but doesn't create a key.

Same for:
- `j.clients.ssh.loadSSHAgent(path="mykey", createkeys=True)`
- `j.clients.ssh.loadSSHAgent(path="~/.ssh/mykey", createkeys=True)`

**Comment by khaledkbadr** [comment]
fixed in https://github.com/Jumpscale/core9/commit/6a2a7739fd3ebfd3f9d30e4976eeb4a6be0f91c7

**Comment by yveskerwyn** [comment]
Please back port to 9.2.0

Moved to https://github.com/Jumpscale/core9/issues/86
